logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8084
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: test
    key-store-type: jks
    key-store-provider: SUN
spring:
  application:
    name: seller
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/seller?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: mandicnikola
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
