INSERT IGNORE  INTO roles(name) VALUES('ROLE_PAYPAL');
INSERT IGNORE  INTO roles(name) VALUES('ROLE_BITCOIN');
INSERT IGNORE  INTO roles(name) VALUES('ROLE_BANK');
INSERT IGNORE  INTO roles(name) VALUES('ROLE_ADMIN');
