#spring.application.name=netflix-zuul-api-gateway-server
#server.port=8765
#
#eureka.client.service-url.default-zone=https://localhost:8761/eureka

spring:
  application:
    name: netflix-zuul-api-gateway-server

server:
  port: 8765
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: test
    key-store-type: jks
    key-store-provider: SUN

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 30000
  routes:
    sample:
      sensitive-headers:
  sslHostnameValidationEnabled: false
ribbon:
  IsSecured: true
  ConnectTimeout:  10000
  ReadTimeout:  10000
  eureka:
    enabled: true
  TrustStore: classpath:keystore.jks
  TrustStorePassword : password
  IsHostnameValidationRequired: false
