

spring:
  application:
    name: lu
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/lu?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: mandicnikola
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8090
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: test
    key-store-type: jks
    key-store-provider: SUN

jwt:
  secret: mysecretbuahahah